export interface Country {
  id: string;       // ISO 3166-1 alpha-3
  name: string;     // Common English name
  borders: string[]; // ISO alpha-3 codes of land-bordering countries
  numericId: string; // ISO 3166-1 numeric code (as string) for world-atlas TopoJSON
}

export const COUNTRIES: Country[] = [
  // ── Africa ──────────────────────────────────────────────────────────────────
  { id: "DZA", name: "Algeria",                  numericId: "12",  borders: ["TUN","LBY","NER","MLI","MRT","ESH","MAR"] },
  { id: "AGO", name: "Angola",                   numericId: "24",  borders: ["COD","ZMB","NAM","COG"] },
  { id: "BEN", name: "Benin",                    numericId: "204", borders: ["NGA","BFA","NER","TGO"] },
  { id: "BWA", name: "Botswana",                 numericId: "72",  borders: ["ZAF","ZWE","ZMB","NAM"] },
  { id: "BFA", name: "Burkina Faso",             numericId: "854", borders: ["MLI","NER","BEN","TGO","GHA","CIV"] },
  { id: "BDI", name: "Burundi",                  numericId: "108", borders: ["COD","RWA","TZA"] },
  { id: "CMR", name: "Cameroon",                 numericId: "120", borders: ["NGA","TCD","CAF","COG","GAB","GNQ"] },
  { id: "CAF", name: "Central African Republic", numericId: "140", borders: ["CMR","TCD","SDN","SSD","COD","COG"] },
  { id: "TCD", name: "Chad",                     numericId: "148", borders: ["LBY","NER","NGA","CMR","CAF","SDN"] },
  { id: "COD", name: "DR Congo",                 numericId: "180", borders: ["CAF","SSD","UGA","RWA","BDI","TZA","ZMB","AGO","COG"] },
  { id: "COG", name: "Republic of the Congo",    numericId: "178", borders: ["GAB","CMR","CAF","COD","AGO"] },
  { id: "CIV", name: "Ivory Coast",              numericId: "384", borders: ["LBR","GIN","MLI","BFA","GHA"] },
  { id: "DJI", name: "Djibouti",                 numericId: "262", borders: ["ETH","ERI","SOM"] },
  { id: "EGY", name: "Egypt",                    numericId: "818", borders: ["LBY","SDN","ISR","PSE"] },
  { id: "GNQ", name: "Equatorial Guinea",        numericId: "226", borders: ["CMR","GAB"] },
  { id: "ERI", name: "Eritrea",                  numericId: "232", borders: ["SDN","ETH","DJI"] },
  { id: "SWZ", name: "Eswatini",                 numericId: "748", borders: ["ZAF","MOZ"] },
  { id: "ETH", name: "Ethiopia",                 numericId: "231", borders: ["ERI","DJI","SOM","KEN","SSD","SDN"] },
  { id: "GAB", name: "Gabon",                    numericId: "266", borders: ["CMR","COG","GNQ"] },
  { id: "GMB", name: "Gambia",                   numericId: "270", borders: ["SEN"] },
  { id: "GHA", name: "Ghana",                    numericId: "288", borders: ["CIV","BFA","TGO"] },
  { id: "GIN", name: "Guinea",                   numericId: "324", borders: ["SEN","GNB","SLE","LBR","CIV","MLI"] },
  { id: "GNB", name: "Guinea-Bissau",            numericId: "624", borders: ["SEN","GIN"] },
  { id: "KEN", name: "Kenya",                    numericId: "404", borders: ["ETH","SOM","TZA","UGA","SSD"] },
  { id: "LSO", name: "Lesotho",                  numericId: "426", borders: ["ZAF"] },
  { id: "LBR", name: "Liberia",                  numericId: "430", borders: ["GIN","SLE","CIV"] },
  { id: "LBY", name: "Libya",                    numericId: "434", borders: ["TUN","DZA","NER","TCD","SDN","EGY"] },
  { id: "MWI", name: "Malawi",                   numericId: "454", borders: ["TZA","ZMB","MOZ"] },
  { id: "MLI", name: "Mali",                     numericId: "466", borders: ["DZA","NER","BFA","CIV","GIN","SEN","MRT"] },
  { id: "MRT", name: "Mauritania",               numericId: "478", borders: ["ESH","DZA","MLI","SEN"] },
  { id: "MAR", name: "Morocco",                  numericId: "504", borders: ["DZA","ESH","ESP"] },
  { id: "MOZ", name: "Mozambique",               numericId: "508", borders: ["TZA","MWI","ZMB","ZWE","ZAF","SWZ"] },
  { id: "NAM", name: "Namibia",                  numericId: "516", borders: ["AGO","ZMB","BWA","ZAF"] },
  { id: "NER", name: "Niger",                    numericId: "562", borders: ["DZA","LBY","TCD","NGA","BEN","BFA","MLI"] },
  { id: "NGA", name: "Nigeria",                  numericId: "566", borders: ["BEN","NER","TCD","CMR"] },
  { id: "RWA", name: "Rwanda",                   numericId: "646", borders: ["UGA","TZA","BDI","COD"] },
  { id: "SEN", name: "Senegal",                  numericId: "686", borders: ["GMB","GNB","GIN","MLI","MRT"] },
  { id: "SLE", name: "Sierra Leone",             numericId: "694", borders: ["GIN","LBR"] },
  { id: "SOM", name: "Somalia",                  numericId: "706", borders: ["ETH","DJI","KEN"] },
  { id: "ZAF", name: "South Africa",             numericId: "710", borders: ["NAM","BWA","ZWE","MOZ","SWZ","LSO"] },
  { id: "SSD", name: "South Sudan",              numericId: "728", borders: ["SDN","ETH","KEN","UGA","COD","CAF"] },
  { id: "SDN", name: "Sudan",                    numericId: "729", borders: ["EGY","LBY","TCD","CAF","SSD","ETH","ERI"] },
  { id: "TZA", name: "Tanzania",                 numericId: "834", borders: ["KEN","UGA","RWA","BDI","COD","ZMB","MWI","MOZ"] },
  { id: "TGO", name: "Togo",                     numericId: "768", borders: ["GHA","BEN","BFA"] },
  { id: "TUN", name: "Tunisia",                  numericId: "788", borders: ["DZA","LBY"] },
  { id: "UGA", name: "Uganda",                   numericId: "800", borders: ["SSD","ETH","KEN","TZA","RWA","COD"] },
  { id: "ESH", name: "Western Sahara",           numericId: "732", borders: ["MAR","DZA","MRT"] },
  { id: "ZMB", name: "Zambia",                   numericId: "894", borders: ["COD","TZA","MWI","MOZ","ZWE","BWA","NAM","AGO"] },
  { id: "ZWE", name: "Zimbabwe",                 numericId: "716", borders: ["ZMB","MOZ","ZAF","BWA"] },

  // ── Asia ────────────────────────────────────────────────────────────────────
  { id: "AFG", name: "Afghanistan",              numericId: "4",   borders: ["IRN","TKM","UZB","TJK","CHN","PAK"] },
  { id: "ARM", name: "Armenia",                  numericId: "51",  borders: ["TUR","GEO","AZE","IRN"] },
  { id: "AZE", name: "Azerbaijan",               numericId: "31",  borders: ["RUS","GEO","ARM","IRN","TUR"] },
  { id: "BGD", name: "Bangladesh",               numericId: "50",  borders: ["IND","MMR"] },
  { id: "BTN", name: "Bhutan",                   numericId: "64",  borders: ["CHN","IND"] },
  { id: "BRN", name: "Brunei",                   numericId: "96",  borders: ["MYS"] },
  { id: "KHM", name: "Cambodia",                 numericId: "116", borders: ["THA","LAO","VNM"] },
  { id: "CHN", name: "China",                    numericId: "156", borders: ["RUS","MNG","KAZ","KGZ","TJK","AFG","PAK","IND","NPL","BTN","MMR","LAO","VNM"] },
  { id: "GEO", name: "Georgia",                  numericId: "268", borders: ["RUS","TUR","ARM","AZE"] },
  { id: "IND", name: "India",                    numericId: "356", borders: ["PAK","CHN","NPL","BTN","BGD","MMR"] },
  { id: "IDN", name: "Indonesia",                numericId: "360", borders: ["MYS","PNG","TLS"] },
  { id: "IRN", name: "Iran",                     numericId: "364", borders: ["TKM","AFG","PAK","IRQ","TUR","ARM","AZE"] },
  { id: "IRQ", name: "Iraq",                     numericId: "368", borders: ["TUR","SYR","JOR","SAU","KWT","IRN"] },
  { id: "ISR", name: "Israel",                   numericId: "376", borders: ["LBN","SYR","JOR","EGY","PSE"] },
  { id: "JOR", name: "Jordan",                   numericId: "400", borders: ["SAU","IRQ","SYR","ISR","PSE"] },
  { id: "KAZ", name: "Kazakhstan",               numericId: "398", borders: ["RUS","CHN","KGZ","UZB","TKM"] },
  { id: "KWT", name: "Kuwait",                   numericId: "414", borders: ["IRQ","SAU"] },
  { id: "KGZ", name: "Kyrgyzstan",               numericId: "417", borders: ["KAZ","CHN","TJK","UZB"] },
  { id: "LAO", name: "Laos",                     numericId: "418", borders: ["CHN","VNM","KHM","THA","MMR"] },
  { id: "LBN", name: "Lebanon",                  numericId: "422", borders: ["SYR","ISR"] },
  { id: "MYS", name: "Malaysia",                 numericId: "458", borders: ["THA","IDN","BRN"] },
  { id: "MNG", name: "Mongolia",                 numericId: "496", borders: ["RUS","CHN"] },
  { id: "MMR", name: "Myanmar",                  numericId: "104", borders: ["CHN","LAO","THA","BGD","IND"] },
  { id: "NPL", name: "Nepal",                    numericId: "524", borders: ["CHN","IND"] },
  { id: "PRK", name: "North Korea",              numericId: "408", borders: ["RUS","CHN","KOR"] },
  { id: "OMN", name: "Oman",                     numericId: "512", borders: ["SAU","YEM","ARE"] },
  { id: "PAK", name: "Pakistan",                 numericId: "586", borders: ["AFG","CHN","IND","IRN"] },
  { id: "PSE", name: "Palestine",                numericId: "275", borders: ["ISR","EGY","JOR"] },
  { id: "QAT", name: "Qatar",                    numericId: "634", borders: ["SAU"] },
  { id: "SAU", name: "Saudi Arabia",             numericId: "682", borders: ["JOR","IRQ","KWT","QAT","ARE","OMN","YEM"] },
  { id: "KOR", name: "South Korea",              numericId: "410", borders: ["PRK"] },
  { id: "SYR", name: "Syria",                    numericId: "760", borders: ["TUR","IRQ","JOR","ISR","LBN"] },
  { id: "TJK", name: "Tajikistan",               numericId: "762", borders: ["KGZ","CHN","AFG","UZB"] },
  { id: "THA", name: "Thailand",                 numericId: "764", borders: ["MMR","LAO","KHM","MYS"] },
  { id: "TLS", name: "Timor-Leste",              numericId: "626", borders: ["IDN"] },
  { id: "TKM", name: "Turkmenistan",             numericId: "795", borders: ["KAZ","UZB","AFG","IRN"] },
  { id: "ARE", name: "United Arab Emirates",     numericId: "784", borders: ["SAU","OMN"] },
  { id: "UZB", name: "Uzbekistan",               numericId: "860", borders: ["KAZ","KGZ","TJK","AFG","TKM"] },
  { id: "VNM", name: "Vietnam",                  numericId: "704", borders: ["CHN","LAO","KHM"] },
  { id: "YEM", name: "Yemen",                    numericId: "887", borders: ["SAU","OMN"] },

  // ── Europe ───────────────────────────────────────────────────────────────────
  { id: "ALB", name: "Albania",                  numericId: "8",   borders: ["MKD","XKX","MNE","GRC"] },
  { id: "AND", name: "Andorra",                  numericId: "20",  borders: ["FRA","ESP"] },
  { id: "AUT", name: "Austria",                  numericId: "40",  borders: ["DEU","CZE","SVK","HUN","SVN","ITA","LIE","CHE"] },
  { id: "BLR", name: "Belarus",                  numericId: "112", borders: ["POL","LTU","LVA","RUS","UKR"] },
  { id: "BEL", name: "Belgium",                  numericId: "56",  borders: ["FRA","LUX","DEU","NLD"] },
  { id: "BIH", name: "Bosnia and Herzegovina",   numericId: "70",  borders: ["HRV","SRB","MNE"] },
  { id: "BGR", name: "Bulgaria",                 numericId: "100", borders: ["ROU","SRB","MKD","GRC","TUR"] },
  { id: "HRV", name: "Croatia",                  numericId: "191", borders: ["SVN","HUN","SRB","BIH","MNE"] },
  { id: "CZE", name: "Czech Republic",           numericId: "203", borders: ["POL","SVK","AUT","DEU"] },
  { id: "DNK", name: "Denmark",                  numericId: "208", borders: ["DEU"] },
  { id: "EST", name: "Estonia",                  numericId: "233", borders: ["RUS","LVA"] },
  { id: "FIN", name: "Finland",                  numericId: "246", borders: ["NOR","SWE","RUS"] },
  { id: "FRA", name: "France",                   numericId: "250", borders: ["BEL","LUX","DEU","CHE","ITA","MCO","AND","ESP"] },
  { id: "DEU", name: "Germany",                  numericId: "276", borders: ["DNK","POL","CZE","AUT","CHE","FRA","LUX","BEL","NLD"] },
  { id: "GRC", name: "Greece",                   numericId: "300", borders: ["ALB","MKD","BGR","TUR"] },
  { id: "HUN", name: "Hungary",                  numericId: "348", borders: ["AUT","SVK","UKR","ROU","SRB","HRV","SVN"] },
  { id: "ITA", name: "Italy",                    numericId: "380", borders: ["FRA","CHE","AUT","SVN","SMR","VAT"] },
  { id: "XKX", name: "Kosovo",                   numericId: "383", borders: ["SRB","MKD","ALB","MNE"] },
  { id: "LVA", name: "Latvia",                   numericId: "428", borders: ["EST","RUS","BLR","LTU"] },
  { id: "LIE", name: "Liechtenstein",            numericId: "438", borders: ["AUT","CHE"] },
  { id: "LTU", name: "Lithuania",                numericId: "440", borders: ["LVA","BLR","POL","RUS"] },
  { id: "LUX", name: "Luxembourg",               numericId: "442", borders: ["FRA","BEL","DEU"] },
  { id: "MDA", name: "Moldova",                  numericId: "498", borders: ["ROU","UKR"] },
  { id: "MCO", name: "Monaco",                   numericId: "492", borders: ["FRA"] },
  { id: "MNE", name: "Montenegro",               numericId: "499", borders: ["HRV","BIH","SRB","XKX","ALB"] },
  { id: "NLD", name: "Netherlands",              numericId: "528", borders: ["BEL","DEU"] },
  { id: "MKD", name: "North Macedonia",          numericId: "807", borders: ["SRB","XKX","ALB","GRC","BGR"] },
  { id: "NOR", name: "Norway",                   numericId: "578", borders: ["SWE","FIN","RUS"] },
  { id: "POL", name: "Poland",                   numericId: "616", borders: ["DEU","CZE","SVK","UKR","BLR","LTU","RUS"] },
  { id: "PRT", name: "Portugal",                 numericId: "620", borders: ["ESP"] },
  { id: "ROU", name: "Romania",                  numericId: "642", borders: ["HUN","SRB","BGR","MDA","UKR"] },
  { id: "RUS", name: "Russia",                   numericId: "643", borders: ["NOR","FIN","EST","LVA","BLR","UKR","GEO","AZE","KAZ","CHN","MNG","PRK","POL","LTU"] },
  { id: "SMR", name: "San Marino",               numericId: "674", borders: ["ITA"] },
  { id: "SRB", name: "Serbia",                   numericId: "688", borders: ["HUN","ROU","BGR","MKD","XKX","BIH","HRV","MNE"] },
  { id: "SVK", name: "Slovakia",                 numericId: "703", borders: ["CZE","AUT","HUN","UKR","POL"] },
  { id: "SVN", name: "Slovenia",                 numericId: "705", borders: ["ITA","AUT","HUN","HRV"] },
  { id: "ESP", name: "Spain",                    numericId: "724", borders: ["PRT","FRA","AND","MAR"] },
  { id: "SWE", name: "Sweden",                   numericId: "752", borders: ["NOR","FIN"] },
  { id: "CHE", name: "Switzerland",              numericId: "756", borders: ["AUT","LIE","DEU","FRA","ITA"] },
  { id: "TUR", name: "Turkey",                   numericId: "792", borders: ["GRC","BGR","GEO","ARM","AZE","IRN","IRQ","SYR"] },
  { id: "UKR", name: "Ukraine",                  numericId: "804", borders: ["RUS","BLR","POL","SVK","HUN","ROU","MDA"] },
  { id: "VAT", name: "Vatican City",             numericId: "336", borders: ["ITA"] },

  // ── Americas ─────────────────────────────────────────────────────────────────
  { id: "ARG", name: "Argentina",                numericId: "32",  borders: ["CHL","BOL","PRY","BRA","URY"] },
  { id: "BLZ", name: "Belize",                   numericId: "84",  borders: ["MEX","GTM"] },
  { id: "BOL", name: "Bolivia",                  numericId: "68",  borders: ["PER","CHL","ARG","PRY","BRA"] },
  { id: "BRA", name: "Brazil",                   numericId: "76",  borders: ["VEN","GUY","SUR","COL","PER","BOL","PRY","ARG","URY"] },
  { id: "CAN", name: "Canada",                   numericId: "124", borders: ["USA"] },
  { id: "CHL", name: "Chile",                    numericId: "152", borders: ["PER","BOL","ARG"] },
  { id: "COL", name: "Colombia",                 numericId: "170", borders: ["VEN","BRA","PER","ECU","PAN"] },
  { id: "CRI", name: "Costa Rica",               numericId: "188", borders: ["NIC","PAN"] },
  { id: "DOM", name: "Dominican Republic",       numericId: "214", borders: ["HTI"] },
  { id: "ECU", name: "Ecuador",                  numericId: "218", borders: ["COL","PER"] },
  { id: "SLV", name: "El Salvador",              numericId: "222", borders: ["GTM","HND"] },
  { id: "GTM", name: "Guatemala",                numericId: "320", borders: ["MEX","BLZ","HND","SLV"] },
  { id: "GUY", name: "Guyana",                   numericId: "328", borders: ["VEN","BRA","SUR"] },
  { id: "HTI", name: "Haiti",                    numericId: "332", borders: ["DOM"] },
  { id: "HND", name: "Honduras",                 numericId: "340", borders: ["GTM","SLV","NIC"] },
  { id: "MEX", name: "Mexico",                   numericId: "484", borders: ["USA","GTM","BLZ"] },
  { id: "NIC", name: "Nicaragua",                numericId: "558", borders: ["HND","CRI"] },
  { id: "PAN", name: "Panama",                   numericId: "591", borders: ["CRI","COL"] },
  { id: "PRY", name: "Paraguay",                 numericId: "600", borders: ["BOL","BRA","ARG"] },
  { id: "PER", name: "Peru",                     numericId: "604", borders: ["ECU","COL","BRA","BOL","CHL"] },
  { id: "SUR", name: "Suriname",                 numericId: "740", borders: ["GUY","BRA"] },
  { id: "USA", name: "United States",            numericId: "840", borders: ["CAN","MEX"] },
  { id: "URY", name: "Uruguay",                  numericId: "858", borders: ["BRA","ARG"] },
  { id: "VEN", name: "Venezuela",                numericId: "862", borders: ["COL","BRA","GUY"] },

  // ── Oceania ──────────────────────────────────────────────────────────────────
  { id: "PNG", name: "Papua New Guinea",         numericId: "598", borders: ["IDN"] },
];

// Build a lookup map for fast access
export const COUNTRY_MAP = new Map<string, Country>(COUNTRIES.map(c => [c.id, c]));
